apiVersion: helm.hops.ops.com.ai/v1alpha1
kind: ArgoWorkflows
metadata:
  name: argo-workflows
  namespace: example-env
spec:
  clusterName: example-cluster
  labels:
    team: platform
  namespace: argo
  values:
    server:
      enabled: true
      extraArgs:
        - --auth-mode=server
    controller:
      metricsConfig:
        enabled: true
      serviceMonitor:
        enabled: true
